package com.sv.quiz_master.user.model;
// Generated May 31, 2016 8:50:58 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QuestionPaper generated by hbm2java
 */
@Entity(name = "com.sv.quiz_master.user.model.QuestionPaper")
@Table(name = "question_paper")
public class QuestionPaper implements java.io.Serializable {

    private Integer indexNo;
    private String description;
    private Date lastUsedOn;
    private int durationPerQuestion;
    private boolean active;

    private Set<Question> questions = new HashSet<Question>(0);

    public QuestionPaper() {
    }

    public QuestionPaper(String description) {
        this.description = description;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "index_no", unique = true, nullable = false)
    public Integer getIndexNo() {
        return this.indexNo;
    }

    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }

    @Column(name = "description", nullable = false, length = 100)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_used_on", length = 19)
    public Date getLastUsedOn() {
        return this.lastUsedOn;
    }

    public void setLastUsedOn(Date lastUsedOn) {
        this.lastUsedOn = lastUsedOn;
    }

    @Column(name = "duration_per_question", nullable = false)
    public int getDurationPerQuestion() {
        return durationPerQuestion;
    }

    public void setDurationPerQuestion(int durationPerQuestion) {
        this.durationPerQuestion = durationPerQuestion;
    }

    @Column(name = "active", nullable = false)
    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "questionPaper")
    public Set<Question> getQuestions() {
        return this.questions;
    }

    public void setQuestions(Set<Question> questions) {
        this.questions = questions;
    }

}
