package com.sv.quiz_master.user.model;
// Generated May 31, 2016 8:50:58 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QuizSessionUser generated by hbm2java
 */
@Entity(name = "com.sv.quiz_master.user.model.QuizSessionUser")
@Table(name = "quiz_session_user")
public class QuizSessionUser implements java.io.Serializable {

    private Integer indexNo;
    private QuizSession quizSession;
    private String name;
    private String nicNo;
    private String mobileNo;
    private String status;
    private Set<QuizSessionUserAnswer> quizSessionUserAnswers = new HashSet<QuizSessionUserAnswer>(0);

    public QuizSessionUser() {
    }

    public QuizSessionUser(QuizSession quizSession, String name, String nicNo, String mobileNo) {
        this.quizSession = quizSession;
        this.name = name;
        this.nicNo = nicNo;
        this.mobileNo = mobileNo;
    }

    public QuizSessionUser(QuizSession quizSession, String name, String nicNo, String mobileNo, Set<QuizSessionUserAnswer> quizSessionUserAnswers) {
        this.quizSession = quizSession;
        this.name = name;
        this.nicNo = nicNo;
        this.mobileNo = mobileNo;
        this.quizSessionUserAnswers = quizSessionUserAnswers;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "index_no", unique = true, nullable = false)
    public Integer getIndexNo() {
        return this.indexNo;
    }

    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "quiz_session", nullable = false)
    public QuizSession getQuizSession() {
        return this.quizSession;
    }

    public void setQuizSession(QuizSession quizSession) {
        this.quizSession = quizSession;
    }

    @Column(name = "name", nullable = false, length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "nic_no", nullable = false, length = 25)
    public String getNicNo() {
        return this.nicNo;
    }

    public void setNicNo(String nicNo) {
        this.nicNo = nicNo;
    }

    @Column(name = "mobile_no", nullable = false, length = 25)
    public String getMobileNo() {
        return this.mobileNo;
    }

    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }

    @Column(name = "status", nullable = false, length = 25)
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "quizSessionUser")
    public Set<QuizSessionUserAnswer> getQuizSessionUserAnswers() {
        return this.quizSessionUserAnswers;
    }

    public void setQuizSessionUserAnswers(Set<QuizSessionUserAnswer> quizSessionUserAnswers) {
        this.quizSessionUserAnswers = quizSessionUserAnswers;
    }

}
