package com.sv.quiz_master.master.model;
// Generated May 31, 2016 8:46:19 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QuestionPaper generated by hbm2java
 */
@Entity(name = "com.sv.quiz_master.master.model.QuestionPaper")
@Table(name = "question_paper")
public class QuestionPaper implements java.io.Serializable {

    private Integer indexNo;
    private String description;
    private Date lastUsedOn;
    private String duration_per_question;
    private int active;
    private Set<QuizSession> quizSessions = new HashSet<QuizSession>(0);
    private Set<Question> questions = new HashSet<Question>(0);
    private Set<QuizSessionUserAnswer> quizSessionUserAnswers = new HashSet<QuizSessionUserAnswer>(0);

    public QuestionPaper() {
    }

    public QuestionPaper(String description) {
        this.description = description;
    }


    public QuestionPaper(Integer indexNo, String description, Date lastUsedOn, String duration_per_question, int active) {
        this.indexNo = indexNo;
        this.description = description;
        this.lastUsedOn = lastUsedOn;
        this.duration_per_question = duration_per_question;
        this.active = active;
    }
    

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "index_no", unique = true, nullable = false)
    public Integer getIndexNo() {
        return this.indexNo;
    }

    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }

    @Column(name = "description", nullable = false, length = 100)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_used_on", length = 19)
    public Date getLastUsedOn() {
        return this.lastUsedOn;
    }

    public void setLastUsedOn(Date lastUsedOn) {
        this.lastUsedOn = lastUsedOn;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "questionPaper")
    public Set<QuizSession> getQuizSessions() {
        return this.quizSessions;
    }

    public void setQuizSessions(Set<QuizSession> quizSessions) {
        this.quizSessions = quizSessions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "questionPaper")
    public Set<Question> getQuestions() {
        return this.questions;
    }

    public void setQuestions(Set<Question> questions) {
        this.questions = questions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "questionPaper")
    public Set<QuizSessionUserAnswer> getQuizSessionUserAnswers() {
        return this.quizSessionUserAnswers;
    }

    public void setQuizSessionUserAnswers(Set<QuizSessionUserAnswer> quizSessionUserAnswers) {
        this.quizSessionUserAnswers = quizSessionUserAnswers;
    }

    /**
     * @return the duration_per_question
     */
    public String getDuration_per_question() {
        return duration_per_question;
    }

    /**
     * @param duration_per_question the duration_per_question to set
     */
    public void setDuration_per_question(String duration_per_question) {
        this.duration_per_question = duration_per_question;
    }

    /**
     * @return the active
     */
    public int isActive() {
        return active;
    }

    /**
     * @param active the active to set
     */
    public void setActive(int active) {
        this.active = active;
    }

}
