package com.sv.quiz_master.master.model;
// Generated May 31, 2016 8:46:19 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QuizSessionUserAnswer generated by hbm2java
 */
@Entity(name = "com.sv.quiz_master.master.model.QuizSessionUserAnswer")
@Table(name = "quiz_session_user_answer")
public class QuizSessionUserAnswer implements java.io.Serializable {

    private Integer indexNo;
    private Question question;
    private QuestionPaper questionPaper;
    private QuizSession quizSession;
    private QuizSessionUser quizSessionUser;
    private String answer;
    private boolean correct;
    private int duration;

    public QuizSessionUserAnswer() {
    }

    public QuizSessionUserAnswer(Question question, QuestionPaper questionPaper, QuizSession quizSession, QuizSessionUser quizSessionUser, String answer, boolean correct, int duration) {
        this.question = question;
        this.questionPaper = questionPaper;
        this.quizSession = quizSession;
        this.quizSessionUser = quizSessionUser;
        this.answer = answer;
        this.correct = correct;
        this.duration = duration;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "index_no", unique = true, nullable = false)
    public Integer getIndexNo() {
        return this.indexNo;
    }

    public void setIndexNo(Integer indexNo) {
        this.indexNo = indexNo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "question", nullable = false)
    public Question getQuestion() {
        return this.question;
    }

    public void setQuestion(Question question) {
        this.question = question;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "question_paper", nullable = false)
    public QuestionPaper getQuestionPaper() {
        return this.questionPaper;
    }

    public void setQuestionPaper(QuestionPaper questionPaper) {
        this.questionPaper = questionPaper;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "quiz_session", nullable = false)
    public QuizSession getQuizSession() {
        return this.quizSession;
    }

    public void setQuizSession(QuizSession quizSession) {
        this.quizSession = quizSession;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "quiz_user", nullable = false)
    public QuizSessionUser getQuizSessionUser() {
        return this.quizSessionUser;
    }

    public void setQuizSessionUser(QuizSessionUser quizSessionUser) {
        this.quizSessionUser = quizSessionUser;
    }

    @Column(name = "answer", nullable = false, length = 25)
    public String getAnswer() {
        return this.answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    @Column(name = "correct", nullable = false)
    public boolean isCorrect() {
        return this.correct;
    }

    public void setCorrect(boolean correct) {
        this.correct = correct;
    }

    @Column(name = "duration", nullable = false)
    public int getDuration() {
        return this.duration;
    }

    public void setDuration(int duration) {
        this.duration = duration;
    }

}
